# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wrest}
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sidu Ponnappa"]
  s.date = %q{2009-09-10}
  s.description = %q{Wrest is a REST client library which allows you to quickly build object oriented wrappers around any web service. It has two main components - Wrest Core and Wrest::Resource.}
  s.email = %q{ckponnappa@gmail.com}
  s.executables = ["wrest", "jwrest"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "bin/jwrest",
    "bin/wrest",
    "bin/wrest_shell.rb",
    "examples/delicious.rb",
    "examples/redirection.rb",
    "examples/twitter.rb",
    "examples/twitter_public_timeline.rb",
    "examples/wow_realm_status.rb",
    "lib/wrest.rb",
    "lib/wrest/components.rb",
    "lib/wrest/components/attributes_container.rb",
    "lib/wrest/components/attributes_container/alias_accessors.rb",
    "lib/wrest/components/attributes_container/typecaster.rb",
    "lib/wrest/components/mutators.rb",
    "lib/wrest/components/mutators/base.rb",
    "lib/wrest/components/mutators/camel_to_snake_case.rb",
    "lib/wrest/components/mutators/xml_mini_type_caster.rb",
    "lib/wrest/components/mutators/xml_simple_type_caster.rb",
    "lib/wrest/components/translators.rb",
    "lib/wrest/components/translators/content_types.rb",
    "lib/wrest/components/translators/json.rb",
    "lib/wrest/components/translators/xml.rb",
    "lib/wrest/core_ext/hash.rb",
    "lib/wrest/core_ext/hash/conversions.rb",
    "lib/wrest/core_ext/string.rb",
    "lib/wrest/core_ext/string/conversions.rb",
    "lib/wrest/exceptions.rb",
    "lib/wrest/http.rb",
    "lib/wrest/http/delete.rb",
    "lib/wrest/http/get.rb",
    "lib/wrest/http/options.rb",
    "lib/wrest/http/post.rb",
    "lib/wrest/http/put.rb",
    "lib/wrest/http/redirection.rb",
    "lib/wrest/http/request.rb",
    "lib/wrest/http/response.rb",
    "lib/wrest/resource.rb",
    "lib/wrest/resource/base.rb",
    "lib/wrest/resource/collection.rb",
    "lib/wrest/resource/state.rb",
    "lib/wrest/uri.rb",
    "lib/wrest/uri_template.rb",
    "lib/wrest/version.rb",
    "spec/custom_matchers/custom_matchers.rb",
    "spec/functional/sample_rails_app/README",
    "spec/functional/sample_rails_app/Rakefile",
    "spec/functional/sample_rails_app/app/controllers/application_controller.rb",
    "spec/functional/sample_rails_app/app/controllers/lead_bottles_controller.rb",
    "spec/functional/sample_rails_app/app/helpers/application_helper.rb",
    "spec/functional/sample_rails_app/app/models/bottle.rb",
    "spec/functional/sample_rails_app/app/models/glass_bottle.rb",
    "spec/functional/sample_rails_app/app/models/lead_bottle.rb",
    "spec/functional/sample_rails_app/config/boot.rb",
    "spec/functional/sample_rails_app/config/database.yml",
    "spec/functional/sample_rails_app/config/environment.rb",
    "spec/functional/sample_rails_app/config/environments/development.rb",
    "spec/functional/sample_rails_app/config/environments/production.rb",
    "spec/functional/sample_rails_app/config/environments/test.rb",
    "spec/functional/sample_rails_app/config/initializers/backtrace_silencers.rb",
    "spec/functional/sample_rails_app/config/initializers/inflections.rb",
    "spec/functional/sample_rails_app/config/initializers/mime_types.rb",
    "spec/functional/sample_rails_app/config/initializers/new_rails_defaults.rb",
    "spec/functional/sample_rails_app/config/initializers/session_store.rb",
    "spec/functional/sample_rails_app/config/locales/en.yml",
    "spec/functional/sample_rails_app/config/routes.rb",
    "spec/functional/sample_rails_app/db/development.sqlite3",
    "spec/functional/sample_rails_app/db/migrate/20090319115628_create_bottle.rb",
    "spec/functional/sample_rails_app/db/schema.rb",
    "spec/functional/sample_rails_app/db/test.sqlite3",
    "spec/functional/sample_rails_app/log/development.log",
    "spec/functional/sample_rails_app/public/404.html",
    "spec/functional/sample_rails_app/public/422.html",
    "spec/functional/sample_rails_app/public/500.html",
    "spec/functional/sample_rails_app/public/favicon.ico",
    "spec/functional/sample_rails_app/public/images/rails.png",
    "spec/functional/sample_rails_app/public/index.html",
    "spec/functional/sample_rails_app/public/robots.txt",
    "spec/functional/sample_rails_app/script/about",
    "spec/functional/sample_rails_app/script/autospec",
    "spec/functional/sample_rails_app/script/console",
    "spec/functional/sample_rails_app/script/dbconsole",
    "spec/functional/sample_rails_app/script/destroy",
    "spec/functional/sample_rails_app/script/generate",
    "spec/functional/sample_rails_app/script/performance/benchmarker",
    "spec/functional/sample_rails_app/script/performance/profiler",
    "spec/functional/sample_rails_app/script/plugin",
    "spec/functional/sample_rails_app/script/runner",
    "spec/functional/sample_rails_app/script/server",
    "spec/functional/sample_rails_app/script/spec",
    "spec/functional/sample_rails_app/script/spec_server",
    "spec/functional/sample_rails_app/test/performance/browsing_test.rb",
    "spec/functional/sample_rails_app/test/test_helper.rb",
    "spec/functional/sample_rails_app/tmtags",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/MIT-LICENSE",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/README.rdoc",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/Rakefile",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/init.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/install.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/base.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/controllers/resources.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/controllers/resources_controller.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/controllers/routes_controller.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/core_extensions/api.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/core_extensions/exception.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/core_extensions/from_json.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/dispatch.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/models/resourced_route.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/query.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render/html.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render/json.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render/xml.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/retrieve.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/version.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/base_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/controllers/resources_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/dispatch_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/models/resourced_route_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/query/parameter_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/query_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render/html_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render/json_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render/xml_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/retrieve_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/spec_helper.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/uninstall.rb",
    "spec/functional/spec_helper.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/unit/spec_helper.rb",
    "spec/unit/wrest/components/attributes_container/alias_accessors_spec.rb",
    "spec/unit/wrest/components/attributes_container/typecaster_spec.rb",
    "spec/unit/wrest/components/attributes_container_spec.rb",
    "spec/unit/wrest/components/mutators/base_spec.rb",
    "spec/unit/wrest/components/mutators/camel_to_snake_spec.rb",
    "spec/unit/wrest/components/mutators/xml_mini_type_caster_spec.rb",
    "spec/unit/wrest/components/mutators/xml_simple_type_caster_spec.rb",
    "spec/unit/wrest/components/mutators_spec.rb",
    "spec/unit/wrest/components/translators/xml_spec.rb",
    "spec/unit/wrest/components/translators_spec.rb",
    "spec/unit/wrest/core_ext/hash/conversions_spec.rb",
    "spec/unit/wrest/core_ext/string/conversions_spec.rb",
    "spec/unit/wrest/http/redirection_spec.rb",
    "spec/unit/wrest/http/request_spec.rb",
    "spec/unit/wrest/http/response_spec.rb",
    "spec/unit/wrest/resource/base_spec.rb",
    "spec/unit/wrest/uri_spec.rb",
    "spec/unit/wrest/uri_template_spec.rb"
  ]
  s.homepage = %q{http://github.com/kaiwren/wrest}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{wrest}
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{REST client library for Ruby.}
  s.test_files = [
    "spec/custom_matchers/custom_matchers.rb",
    "spec/functional/sample_rails_app/app/controllers/application_controller.rb",
    "spec/functional/sample_rails_app/app/controllers/lead_bottles_controller.rb",
    "spec/functional/sample_rails_app/app/helpers/application_helper.rb",
    "spec/functional/sample_rails_app/app/models/bottle.rb",
    "spec/functional/sample_rails_app/app/models/glass_bottle.rb",
    "spec/functional/sample_rails_app/app/models/lead_bottle.rb",
    "spec/functional/sample_rails_app/config/boot.rb",
    "spec/functional/sample_rails_app/config/environment.rb",
    "spec/functional/sample_rails_app/config/environments/development.rb",
    "spec/functional/sample_rails_app/config/environments/production.rb",
    "spec/functional/sample_rails_app/config/environments/test.rb",
    "spec/functional/sample_rails_app/config/initializers/backtrace_silencers.rb",
    "spec/functional/sample_rails_app/config/initializers/inflections.rb",
    "spec/functional/sample_rails_app/config/initializers/mime_types.rb",
    "spec/functional/sample_rails_app/config/initializers/new_rails_defaults.rb",
    "spec/functional/sample_rails_app/config/initializers/session_store.rb",
    "spec/functional/sample_rails_app/config/routes.rb",
    "spec/functional/sample_rails_app/db/migrate/20090319115628_create_bottle.rb",
    "spec/functional/sample_rails_app/db/schema.rb",
    "spec/functional/sample_rails_app/test/performance/browsing_test.rb",
    "spec/functional/sample_rails_app/test/test_helper.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/init.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/install.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/base.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/controllers/resources.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/controllers/resources_controller.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/controllers/routes_controller.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/core_extensions/api.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/core_extensions/exception.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/core_extensions/from_json.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/dispatch.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/models/resourced_route.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/query.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render/html.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render/json.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render/xml.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/render.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/retrieve.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full/version.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/lib/resource_full.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/base_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/controllers/resources_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/dispatch_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/models/resourced_route_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/query/parameter_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/query_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render/html_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render/json_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render/xml_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/render_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/resource_full/retrieve_spec.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/spec/spec_helper.rb",
    "spec/functional/sample_rails_app/vendor/plugins/resource_full/uninstall.rb",
    "spec/functional/spec_helper.rb",
    "spec/unit/spec_helper.rb",
    "spec/unit/wrest/components/attributes_container/alias_accessors_spec.rb",
    "spec/unit/wrest/components/attributes_container/typecaster_spec.rb",
    "spec/unit/wrest/components/attributes_container_spec.rb",
    "spec/unit/wrest/components/mutators/base_spec.rb",
    "spec/unit/wrest/components/mutators/camel_to_snake_spec.rb",
    "spec/unit/wrest/components/mutators/xml_mini_type_caster_spec.rb",
    "spec/unit/wrest/components/mutators/xml_simple_type_caster_spec.rb",
    "spec/unit/wrest/components/mutators_spec.rb",
    "spec/unit/wrest/components/translators/xml_spec.rb",
    "spec/unit/wrest/components/translators_spec.rb",
    "spec/unit/wrest/core_ext/hash/conversions_spec.rb",
    "spec/unit/wrest/core_ext/string/conversions_spec.rb",
    "spec/unit/wrest/http/redirection_spec.rb",
    "spec/unit/wrest/http/request_spec.rb",
    "spec/unit/wrest/http/response_spec.rb",
    "spec/unit/wrest/resource/base_spec.rb",
    "spec/unit/wrest/uri_spec.rb",
    "spec/unit/wrest/uri_template_spec.rb",
    "examples/delicious.rb",
    "examples/redirection.rb",
    "examples/twitter.rb",
    "examples/twitter_public_timeline.rb",
    "examples/wow_realm_status.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<json>, [">= 1.1.3"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<json>, [">= 1.1.3"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.2"])
    s.add_dependency(%q<json>, [">= 1.1.3"])
  end
end
