# frozen_string_literal: true
# A sample Gemfile
source 'http://rubygems.org'

gem 'i18n', '= 0.4.1'
gem 'rake'
gem 'sinatra', '= 1.0'
gem 'wrest', path: '../../'

group :test do
  gem 'rack-test', '0.5.4', require: 'rack/test'
  gem 'rspec', '~> 3.0.0'
end
